//> using scala "3.3.7"
//> using jvm "21"
//> using dep "dev.zio::zio::2.1.26"
//> using dep "dev.zio::zio-streams::2.1.26"
//> using dep "dev.zio::zio-json::0.9.2"
//> using dep "org.scalanlp::breeze::2.1.0"
//> using dep "org.scalanlp::breeze-natives::2.1.0"
//> using dep "org.apache.commons:commons-math3:3.6.1"
//> using test.dep org.scalameta::munit::1.3.3